#In real world i would not store secret inside project but in different remote location
apiVersion: v1
kind: Secret
metadata:
  name: internalservice-secret
# opaque is default for key-value pairs
type: Opaque
data:
  #It has to be base64 encoded
  secret-val: c3VwZXJTZWNyZXQ=
